### PR TITLE
fix: win variables to finish when the player wins

### LINKED ISSUE #12: Game Dont finish when the player wins
![image](https://user-images.githubusercontent.com/44327650/134819743-57c5b34b-37b9-4e86-97fc-c3bcf80f4cfe.png

As you can see in the image, even when the player finds all the cells that are not bombs

### PR DESCRIPTION
**Pull request by kdroppelmann**

### CODE REVIEW

File: test/board_model_test.rb [hunk 1]
```diff
@@ -56,4 +56,11 @@ def test_fill_board_with_bombs
       end
     end
   end
+
+  def test_win
+    puts "test win: #{@board.winner}"
```
Comment (tpcantergiani) [inline test/board_model_test.rb]: THis print is not necesary

File: lib/board_model.rb [hunk 2]
```diff
@@ -130,13 +130,13 @@ def equal(other_board)
   end
 
   def winner
-    count = 0
+    @count = 0
```
Comment (tpcantergiani) [inline lib/board_model.rb]: count is a function variable, not a class atribute, it should begin with '@' @kdroppelmann

**Review by tpcantergiani — APPROVED** [review]
